[General]
LoadColor=#1d1c21

[Background]
Color=#1d1c21
ImageFile=bitterskies.jpg
Type=5

[Presentation]
WallpaperMode=0
WallpaperSource=3
WallpaperFit=0
FocalX=500
FocalY=420
BlackReplacement=#1d1c21
UiPrimary=#4a4358
UiSecondary=#b99fb5
UiAccent=#75617e
UiText=#f7e7ee
UiFont=SMW2: Yoshi's Island
UiFontSize=18
ShellMode=0

[Foreground]
Color=#ffffff
Margin=65
Opacity=0
Padding=10
Position=0
Rounding=0
RoundingDisabled=10
Width=700

[ForegroundBlur]
Enabled=false
Radius=32

[ForegroundShadow]
Color=#ffffff
Enabled=false
Offset=2
Radius=8

[Spacings]
IndentFirstLine=false
LineSpacing=100
ParagraphAbove=0
ParagraphBelow=0
TabWidth=48

[Text]
Color=#ffffff
Font="Times New Roman,12,-1,5,50,0,0,0,0,0"
Misspelled=#ff0000
