Name=Hunter Terminal

[General]
LoadColor=#172a3a

[Background]
Color=#172a3a
ImageFile=
Type=0

[Presentation]
WallpaperMode=5
WallpaperSource=1
WallpaperFit=0
FocalX=500
FocalY=500
BlackReplacement=#172a3a
UiPrimary=#245267
UiSecondary=#42c6c8
UiAccent=#183f52
UiText=#8ce9df
UiFont=Filgaia
UiFontSize=18
ShellMode=1

[Foreground]
Color=#1b3444
Margin=1
Opacity=100
Padding=24
Position=1
Rounding=0
RoundingDisabled=1
Width=700

[ForegroundBlur]
Enabled=false
Radius=1

[ForegroundShadow]
Color=#172a3a
Enabled=false
Offset=0
Radius=1

[Spacings]
IndentFirstLine=false
LineSpacing=110
ParagraphAbove=0
ParagraphBelow=6
TabWidth=32

[Text]
Color=#8ce9df
Font=Filgaia,14,-1,5,50,0,0,0,0,0
VirtualPixelHeight=8
Misspelled=#ef8294
