[General]
LoadColor=#000000

[Background]
Color=#000000
ImageFile=
Type=0

[Presentation]
WallpaperMode=5
WallpaperSource=1
WallpaperFit=0
FocalX=500
FocalY=500
BlackReplacement=#052310
UiPrimary=#0a5c2d
UiSecondary=#29a85b
UiAccent=#063d20
UiText=#9dffc0
UiFont=Filgaia
UiFontSize=18
ShellMode=1

[Foreground]
Color=#000000
Margin=65
Opacity=0
Padding=10
Position=1
Rounding=0
RoundingDisabled=10
Width=700

[ForegroundBlur]
Enabled=false
Radius=32

[ForegroundShadow]
Color=#000000
Enabled=false
Offset=2
Radius=8

[Spacings]
IndentFirstLine=false
LineSpacing=100
ParagraphAbove=0
ParagraphBelow=0
TabWidth=48

[Text]
Color=#0cf155
Font="Courier New,12,-1,5,50,0,0,0,0,0"
Misspelled=#0d5322
