Name=Pastel Meadow

[General]
LoadColor=#bde6ee

[Background]
Color=#bde6ee
ImageFile=
Type=0

[Presentation]
WallpaperMode=5
WallpaperSource=1
WallpaperFit=0
FocalX=500
FocalY=500
BlackReplacement=#293142
UiPrimary=#579b68
UiSecondary=#f1cf68
UiAccent=#315f50
UiText=#493158
UiFont=SMW2: Yoshi's Island
UiFontSize=18
ShellMode=0

[Foreground]
Color=#fff3d8
Margin=1
Opacity=100
Padding=24
Position=1
Rounding=0
RoundingDisabled=1
Width=700

[ForegroundBlur]
Enabled=false
Radius=1

[ForegroundShadow]
Color=#293142
Enabled=false
Offset=0
Radius=1

[Spacings]
IndentFirstLine=false
LineSpacing=115
ParagraphAbove=0
ParagraphBelow=8
TabWidth=32

[Text]
Color=#493158
Font=SMW2: Yoshi's Island,14,-1,5,50,0,0,0,0,0
VirtualPixelHeight=8
Misspelled=#d8666f
