[General]
LoadColor=#5d3e3d

[Background]
Color=#000000
ImageFile=spacedreams.jpg
Type=5

[Presentation]
WallpaperMode=0
WallpaperSource=3
WallpaperFit=0
FocalX=500
FocalY=400
BlackReplacement=#241d31
UiPrimary=#62517c
UiSecondary=#c7b2d9
UiAccent=#3d3159
UiText=#faecff
UiFont=SMW2: Yoshi's Island
UiFontSize=18
ShellMode=0

[Foreground]
Color=#beaf9b
Margin=65
Opacity=50
Padding=10
Position=1
Rounding=10
RoundingDisabled=0
Width=700

[ForegroundBlur]
Enabled=true
Radius=32

[ForegroundShadow]
Color=#000000
Enabled=true
Offset=2
Radius=16

[Spacings]
IndentFirstLine=false
LineSpacing=100
ParagraphAbove=0
ParagraphBelow=0
TabWidth=48

[Text]
Color=#000000
Font="Times New Roman,12,-1,5,50,0,0,0,0,0"
Misspelled=#ff0000
