[General]
LoadColor=#99aab8

[Background]
Color=#99aab8
ImageFile=spygames.jpg
Type=5

[Presentation]
WallpaperMode=2
WallpaperSource=3
WallpaperFit=2
FocalX=520
FocalY=460
BlackReplacement=#1e3542
UiPrimary=#3a687d
UiSecondary=#9ac3c4
UiAccent=#274d60
UiText=#e4f8ed
UiFont=Filgaia
UiFontSize=18
ShellMode=1

[Foreground]
Color=#dee8f1
Margin=65
Opacity=80
Padding=10
Position=1
Rounding=0
RoundingDisabled=10
Width=700

[ForegroundBlur]
Enabled=true
Radius=32

[ForegroundShadow]
Color=#3a4d5e
Enabled=true
Offset=0
Radius=4

[Spacings]
IndentFirstLine=false
LineSpacing=100
ParagraphAbove=0
ParagraphBelow=0
TabWidth=48

[Text]
Color=#000000
Font="Times New Roman,12,-1,5,50,0,0,0,0,0"
Misspelled=#ff0000
