[General]
LoadColor=#d2dadd

[Background]
Color=#d2dadd
ImageFile=tranquility.jpg
Type=5

[Presentation]
WallpaperMode=1
WallpaperSource=3
WallpaperFit=1
FocalX=500
FocalY=440
BlackReplacement=#344852
UiPrimary=#7196a0
UiSecondary=#d9e8e5
UiAccent=#4f747b
UiText=#1c3038
UiFont=SMW2: Yoshi's Island
UiFontSize=18
ShellMode=0

[Foreground]
Color=#ffffff
Margin=65
Opacity=0
Padding=10
Position=1
Rounding=0
RoundingDisabled=10
Width=700

[ForegroundBlur]
Enabled=false
Radius=32

[ForegroundShadow]
Color=#000000
Enabled=false
Offset=2
Radius=8

[Spacings]
IndentFirstLine=false
LineSpacing=100
ParagraphAbove=0
ParagraphBelow=0
TabWidth=48

[Text]
Color=#000000
Font="Times New Roman,12,-1,5,50,0,0,0,0,0"
Misspelled=#ff0000
